raspberry_pis:
  hosts:
    raspberrypi0:
      ansible_host: 10.0.0.127
      ansible_user: rpi0
    raspberrypi1:
      ansible_host: 10.0.0.121
    raspberrypi2:
      ansible_host: 10.0.0.28
    raspberrypi3:
      ansible_host: 10.0.0.18
  
dns:
  hosts:
    raspberrypi0:

nucs:
  hosts:
    nuc0:
      ansible_host: 192.168.1.56
      ansible_user: nuc0
    nuc1:
      ansible_host: 192.168.1.223
      ansible_user: nuc1
    nuc2:
      ansible_host: 192.168.1.25
      ansible_user: nuc2

k3s_nodes:
  children:
    nucs:

k3s_masters:
 hosts:  
  nuc0:

k3s_workers:
  hosts:
    nuc1:
